[package]
name = "capp"
version = "0.3.2"
edition = "2021"
license = "MIT"
authors = ["oiwn"]
description = "Common things i use to build Rust CLI tools for web crawlers."
homepage = "https://github.com/oiwn/capp-rs"
repository = "https://github.com/oiwn/capp-rs"
readme = "README.md"
keywords = ["mini-celery", "async", "executor"]
categories = ["asynchronous", "web-programming", "concurrency"]
exclude = [
    "tmp/*",
    # "benches/*",
    "html/*",
    ".github/*",
    ".gitignore",
    ".tmuxp.yaml",
    "notes.org"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1.74" }
backoff = { version = "0.4.0", optional = true, features = ["tokio"] }
derive_builder = { version = "0.12.0" }
reqwest = { version = "0.11.20", features = ["gzip", "rustls-tls"], optional = true }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.106" }
serde_yaml = "0.9.25"
thiserror = { version = "1.0.48" }
tokio = { version = "1.32.0", features = ["full"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
# hyper = { version = "0.14", features = ["server"] }
hyper = { version = "1.0", features = ["server", "http1"] }
rustis = { version = "0.12.0", features = ["tokio-runtime"], optional = true }
once_cell = "1.18.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = "1.0.75"
http-body-util = "0.1.0"
bytes = "1.5.0"
pin-project-lite = "0.2.13"
tracing-futures = "0.2.5"
tower = "0.4.13"
futures = "0.3.29"

[dev-dependencies]
capp = { path = ".", features = ["http", "healthcheck", "redis"] }
mongodb = { version = "2.6.1", features = ["tokio-runtime"] }
scraper = "0.17.1"
dotenvy = "0.15.7"

[features]
http = ["dep:backoff", "dep:reqwest"]
healthcheck = ["dep:reqwest"]
redis = ["dep:rustis"]
