[workspace]
resolver = "2"
members = [
    "app-context",
    "capp"
]

[workspace.dependencies]
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
thiserror = "1"
anyhow = "1"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Utils
derive_builder = "0.2"
