[package]
name = "capp"
version = "0.2.1"
edition = "2021"
license = "MIT"
authors = ["oiwn"]
description = "Common things i use to build Rust CLI tools for web crawlers."
homepage = "https://github.com/oiwn/capp-rs"
repository = "https://github.com/oiwn/capp-rs"
readme = "README.md"
keywords = ["mini-celery", "async", "executor"]
categories = ["asynchronous", "web-programming", "concurrency"]
exclude = [
    "tmp/*",
    # "benches/*",
    "html/*",
    ".github/*",
    ".gitignore",
    ".tmuxp.yaml",
    "notes.org"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "task_deport",
    "task_executor",
]

[dependencies]
async-trait = { version = "0.1.74" }
task_deport = { path = "./task_deport", optional = true }
task_executor = { path = "./task_executor", optional = true }
backoff = { version = "0.4.0", optional = true, features = ["tokio"] }
chrono = { version = "0.4.3", optional = true, features = ["serde"] }
derive_builder = { version = "0.12.0" }
futures = { version = "0.3.28", optional = true } 
reqwest = { version = "0.11.20", features = ["gzip", "rustls-tls"], optional = true }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.106", optional = true }
serde_yaml = "0.9.25"
thiserror = { version = "1.0.48" }
tokio = { version = "1.32.0", features = ["full"], optional = true}
uuid = { version = "1.4.1", features = ["v4", "serde"], optional = true }
hyper = { version = "0.14", features = ["server"] }
rustis = { version = "0.12.0", features = ["tokio-runtime"], optional = true }
once_cell = "1.18.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
capp = { path = ".", features = ["http", "healthcheck", "executor", "redis"] }
task_deport = { path = "./task_deport", features = ["redis"] }
# hyper = { version = "0.14.27", features = ["server"] }
# hyper = { version = "1.0.0-rc.4", features = ["server"] }
serde_json = "1.0.106"
mongodb = { version = "2.6.1", features = ["tokio-runtime"] }
scraper = "0.17.1"

[features]
http = ["dep:backoff", "dep:reqwest"]
healthcheck = ["dep:reqwest", "dep:tokio"]
redis = ["dep:rustis", "task_deport/redis"]
executor = [ "dep:task_deport", "dep:task_executor"]
# executor = ["dep:tokio", "dep:async-trait", "dep:chrono", "dep:futures", "dep:uuid", "dep:serde_json", "dep:task_deport"]

# size optimization
[profile.release]
opt-level = "s" # or "z" for more aggressive size optimization
lto = true # Enable Link Time Optimization
codegen-units = 1 # Reduce parallel code generation units to maximize optimizations
