[package]
name = "capp"
version = "0.1.9"
edition = "2021"
license = "MIT"
authors = ["oiwn"]
description = "Common things i use to build Rust CLI tools for web crawlers."
homepage = "https://github.com/oiwn/capp-rs"
repository = "https://github.com/oiwn/capp-rs"
readme = "README.md"
keywords = ["mini-celery", "async", "executor"]
categories = ["asynchronous", "web-programming", "concurrency"]
exclude = [
    "tmp/*",
    # "benches/*",
    "html/*",
    ".github/*",
    ".gitignore",
    ".tmuxp.yaml",
    "notes.org"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "task_deport"
]

[dependencies]
task_deport = { path = "./task_deport", optional = true }
async-trait = { version = "0.1.68", optional = true }
backoff = { version = "0.4.0", optional = true, features = ["tokio"] }
chrono = { version = "0.4.24", optional = true, features = ["serde"] }
derive_builder = "0.12.0"
futures = { version = "0.3.28", optional = true } 
log = { version = "0.4.17", optional = true }
reqwest = { version = "0.11.16", features = ["gzip", "rustls-tls"], optional = true }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = { version = "1.0.96", optional = true }
serde_yaml = "0.9.21"
thiserror = { version = "1.0.40", optional = true }
tokio = { version = "1.27.0", features = ["full"], optional = true}
uuid = { version = "1.3.2", features = ["v4", "serde"], optional = true }
regex = "1.8.2"
once_cell = "1.17.1"

[dev-dependencies]
capp = { path = ".", features = ["http", "healthcheck", "executor"] }
hyper = { version = "0.14.26", features = ["server"] }
serde_json = "1.0.96"
simple_logger = "4.1.0"
rustis = { version = "0.11.0", features = ["tokio-runtime"] }
mongodb = { version = "2.5.0", features = ["tokio-runtime"] }
scraper = "0.16.0"
once_cell = "1.17.1"

[features]
http = ["dep:backoff", "dep:reqwest", "dep:log"]
healthcheck = ["dep:reqwest", "dep:log", "dep:tokio"]
executor = ["dep:tokio", "dep:log", "dep:thiserror", "dep:async-trait", "dep:chrono", "dep:futures", "dep:uuid", "dep:serde_json", "dep:task_deport"]

# size optimization
[profile.release]
opt-level = "s" # or "z" for more aggressive size optimization
lto = true # Enable Link Time Optimization
codegen-units = 1 # Reduce parallel code generation units to maximize optimizations

