app:
  name: "HackerNews"
  threads: 2
  max_queue: 500
  proxy_provider: "no_proxy"
  user_agents_file: "examples/hackernews/hn_uas.txt"

no_proxy:
  connect_timeout: 5
  timeout: 30
  proxy:
    use: false
