[package]
name = "capp-queue"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, optional = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
rustis = { version = "0.13", features = ["tokio-runtime"], optional = true }
mongodb = { version = "3", optional = true }
futures = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true }
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "json", "uuid", "chrono" ], optional = true }

[dev-dependencies]
dotenvy = "0.15"
tokio = { version = "1.41", features = ["full", "test-util"] }
serial_test = "3"

[features]
redis = ["dep:tokio", "dep:rustis"]
mongodb = ["dep:tokio", "dep:futures", "dep:futures-util", "dep:mongodb"]
postgres = ["dep:tokio", "dep:sqlx"]
