app:
  name: "HackerNews"
  threads: 2
  max_queue: 500
  user_agents_file: "examples/hn_uas.txt"

http:
  proxy:
    use: true
    uri: http://bro:admin@proxygate1.com:42042
  timeout: 30
  connect_timeout: 10

