[package]
name = "capp-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, optional = true }
tokio = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

backoff = { version = "0.4", optional = true, features = ["tokio"] }
regex = { version = "1.11" }
indexmap = { version = "2.6", optional = true }
url = { version = "2.5", optional = true }
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3"

[features]
http = ["dep:reqwest", "dep:backoff"]
router = ["dep:indexmap", "dep:url"]
